### ISSUE TITLE
Fix leading minuses on E1

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#12]
Looks like the handling of leading minuses in systems is not correct. The solution to part (a) of this one should have a leading minus in the fourth equation, but does not.

![Screen Shot 2021-01-25 at 1 52 15 PM](https://user-images.githubusercontent.com/30658947/105759081-a01ae080-5f15-11eb-90c5-075d12b005a8.png)

**Comment by siwelwerd** [comment]
Actually, I am wondering if the issue might be within Checkit, namely this function

https://github.com/StevenClontz/checkit/blob/d9142d024196f889913fe747cc70a5f7a0106dce/scripts/generator.sage#L53

**Comment by StevenClontz** [comment]
Yes, this is a CheckIt issue; I need to fix it there, and then this bank will be fixed the next time it's built.

**Comment by StevenClontz** [comment]
The public bank is now fixed: https://checkit.clontz.org/#/banks/tbil-la/E1/3

As an aside: seed 3 of E1 and E3 use the same matrix (because they're seeded by the same number, and the matrix is generated before other random elements of each outcome). I'm trying to decide if this is desirable behavior (or should randomness be based e,g, on a seed that's not just the version number, but also a hash of the bank and outcome slugs).

**Comment by StevenClontz** [comment]
Also the bug that caused this to happen was completely avoidable and I'm a very silly person for not anticipating it! https://github.com/StevenClontz/checkit/commit/25d7fb6a20bf13b59a17c3694d4e79d2fdf4ffbb
