### ISSUE TITLE
Make language clearer (e.g. statements->claims) on V2, etc.

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/checkit-tbil-la#19]
Repost https://github.com/StevenClontz/checkit-svelte/issues/10 from @EiriniKilikian

> In the Linear Algebra questions, V2 Linear Combinations, the solutions to some questions in a) and b) are contradicting:
> 
> e.g. Question 15: the solution states (incorrectly) in a) that the associated linear system has no solutions; and in b) it states that there is a linear combination of the columns of the matrix that equal the vector of constants.

**Comment by StevenClontz** [comment]
So technically there isn't an error here. Part (a) asks to rewrite the claim, which happens to be a false claim since it contradicts part (b). However, maybe the answer should include the sentence "This claim is false."? I haven't taught with this version so @siwelwerd has the best insight here.

**Comment by siwelwerd** [comment]
I don't think there is any "technically" needed; this is not an error, but a design choice aimed to get students to translate statements about vector properties into statements about solutions to a vector equation.

The prompts are phrased like this because the kind of prompts we used to use, e.g. "Explain why these vectors are linearly independent or linearly dependent" would result in students writing things like "Every column is a pivot column so they are linearly independent". Students would feel this was an "explanation", but we wanted a deeper explanation connecting the statement back to solutions of a vector equation.

I often have students disregard the prompts, but manage to write down the correct vector equation, solve it, and make a statement such as "There is a solution (to this vector equation), so it is a linear combination", which satisfies the learning goal here. Shifting to this kind of prompt increased the frequency of this on early attempts (I used to get *really* tired of writing things like "But why does having every column be a pivot column mean the vectors are linearly independent?").  

So I read in Steven's comment two suggestions that might be helpful:
1.  Would it be better to call these "claims" than "statements"?
2. Would it be helpful to rewrite the answer for part (b) as "The given statement/claim is false.  [vector] is in fact a linear combination of [other vectors]"?

Those are both easy fixes I am happy to make if they would be helpful.  I don't see an obvious way they would hurt anything.

Please let us know any other questions/suggestions you have @EiriniKilikian !

**Comment by siwelwerd** [comment]
One other related issue I've seen but don't have a good answer for: sometimes students will do part (a) correctly and then for part (b) write things like "My statement is true because [vector] is a linear combination of the other vectors", which is kind of backwards.

**Comment by StevenClontz** [comment]
1. I like calling them claims.
2. I think for the short answer we only need to provide that the claim is true/false, at least, I think that's all I'd want as a quick reference for grading.

For your other comment, maybe the word "directly" would disambiguate?

**Comment by EiriniKilikian** [comment]
Hello everyone,

Thank you for looking into this so promptly. It seems that I didn't read
the questions carefully enough - I see your point, and the questions and
solutions are fine as they are.

I will make sure to emphasize this with my students, especially the ones
who brought this to my attention.

Best,
Eirini
______________________________________________

Virginia Eirini Kilikian, Ph.D.
MAA Project NExT fellow, Silver '19
(pronouns: she/her/hers)
Assistant Professor, Department of Mathematical Sciences
University of Delaware
Ewing Hall 306
Newark, DE 19716
Office phone: (302) 831-1007
++++++++++++++++++++++++++++++++++++
Personal Zoom room: <http://goog_338735105>https://udel.zoom.us/j/4726764799

**Comment by StevenClontz** [comment]
Based on feedback we've received on various V2ish outcomes, I propose we change such exercises to read as follows:

> Consider the following statements.
>
> - (an affirmative statement about spanning, being independent, a basis, etc.)
> - (the contradiction of this statement)
> 
> 1. Write equivalent statements for each (involving what we want to see).
> 2. Show which one of these statements is true.

In the answer, we only supply a relevant RREF calculation, and the true statement.

**Comment by StevenClontz** [comment]
Let me take a stab at V2 and V3 and see what you think of those implementations.

**Comment by StevenClontz** [comment]
V3

![image](https://user-images.githubusercontent.com/1559632/129288948-f7bf86e6-db23-4d11-a46b-e99efe582276.png)

V5

![image](https://user-images.githubusercontent.com/1559632/129288988-3686cca3-9733-4488-950d-a24a88b5f43d.png)

NB sometimes spanning questions have 5 vectors (but still have 50/50 shot at spanning), and independence questions sometimes have 3 vectors (50/50 chance of independence).
