### ISSUE TITLE
V3 errors

### ISSUE THREAD

**Issue by StevenGubkin** [TeamBasedInquiryLearning/checkit-tbil-la#27]
V3#2, for example, claims that the vectors do span R^4 even though RREF of the matrix of column vectors contains a row of zeros.

Similarly V3#4 claims the vectors do not span R^4, when they actually do.

I cannot characterize which problems are generating incorrect solutions.  Maybe these are the situations where the claim in part (a) is false?

**Comment by StevenClontz** [comment]
I think I have this fixed, incorporating changes we want to make from #19. Example:

![image](https://user-images.githubusercontent.com/1559632/124972068-8b2b9880-dfef-11eb-8836-0a004479e110.png)

Fix is in 61fe00bb07ab9e2dd64abd0bf27cd3f0290644a4 - thoughts @siwelwerd before I work on refactoring the rest of the V outcomes similarly?

**Comment by siwelwerd** [comment]
Wait, was the issue a true instead of True? :facepalm:  The change is good. How do we feel about part (b) saying further "The claim is false. The vector equation ... is consistent for every v \in R^4, so the set of vectors .... does span R^4" ?

**Comment by StevenClontz** [comment]
`true==True` in Sage: https://github.com/PreTeXtBook/pretext-cli/issues/122 `True` is what's used in Python, so if I ever write a checkit style guide I'd encourage the Pythonic version. Anyway, I didn't check what was wrong originally since the refactor needed some new logic anyway.

I was actually going to suggest only providing "The claim is true/false" along with the RREF in our generated answers. I'm afraid students will see the similar part (a)s and your proposal for part (b) and treat it as boilerplate they just have canned for their own responses, rather than thinking about what we're aiming for them to think about. But I'm a year rusty on teaching LA so I'll defer to your perspective here.

**Comment by StevenClontz** [comment]
> > I was actually going to suggest only providing "The claim is true/false" along with the RREF in our generated answers.
> 
> Let me know if I can run with this.

Actually moving this discussion to #19
